function:
  handler: src/realtime/movement-rt.handler 
  name: omni-live-real-time-movement-${self:provider.stage}
  description: LiVe Movement Table - ${self:provider.stage}
  tags:
    Name: omni-live-real-time-movement-${self:provider.stage}
  # layers:
  #   - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python311:12
  timeout: 600
  package:
    patterns:
      - '!**/*'
      - 'src/realtime/movement-rt.py'
      - 'src/shared/**'
  events:
    - s3:
        bucket: dms-dw-etl-lvlp
        event: s3:ObjectCreated:*
        rules:
          - prefix: dev/dbo/movement/
        existing: true
  environment:
    MOVEMENT_ORDERS_DB: ${ssm:/omni-pb-rt/${self:provider.stage}/movement/db}
    S3_BUCKET: 'dms-dw-etl-lvlp'
    REGION: ${self:provider.region}
