function:
  handler: src/realtime/movementOrderRT.handler 
  name: omni-live-real-time-movement-order-${self:provider.stage}
  description: LiVe Movement Order Table - ${self:provider.stage}
  runtime: python3.10
  tags:
    Name: omni-live-real-time-movement-order-${self:provider.stage}
  layers:
    - { Ref: PythonPackagesLambdaLayer }
  timeout: 600
  package:
    patterns:
      - '!**/*'
      - 'src/realtime/movementorderrt.py'
      - 'src/shared/**'
  events:
    - s3:
        bucket: dms-dw-etl-lvlp
        event: s3:ObjectCreated:*
        rules:
          - prefix: dev/dbo/movement_order/
        existing: true
  environment:
    LIVE_MOVEMENT_ORDER_DB: ${ssm:/omni-pb-rt/${self:provider.stage}/movement-order/db}
    S3_BUCKET: 'dms-dw-etl-lvlp'
    REGION: ${self:provider.region}
