function:
  handler: src/realtime/ordersRT.handler 
  name: omni-live-real-time-orders-${self:provider.stage}
  description: LiVe Orders Table - ${self:provider.stage}
  runtime: python3.11
  layers:
    - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python311:12
  timeout: 600
  package:
    patterns:
      - '!**/*'
      - 'src/realtime/ordersRT.py'
      - 'src/shared/**'
  events:
    - s3:
        bucket: dms-dw-etl-lvlp
        event: s3:ObjectCreated:*
        rules:
          - prefix: dev/dbo/orders/
        existing: true
  environment:
    LIVE_ORDERS_DB: 'omni-live-orders-dev'
    S3_BUCKET: 'dms-dw-etl-lvlp'
    REGION: ${self:provider.region}
