function:
  handler: src/realtime/orders-rt.handler 
  name: omni-live-real-time-orders-${self:provider.stage}
  description: LiVe Orders Table - ${self:provider.stage}
  tags:
    Name: omni-live-real-time-orders-${self:provider.stage}
  layers:
    - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python311:12
  timeout: 600
  package:
    patterns:
      - '!**/*'
      - 'src/realtime/orders-rt.py'
      - 'src/shared/**'
  events:
    - s3:
        bucket: ${ssm:/omni-realtime/${self:provider.stage}/lvlp/s3-bucket}
        event: s3:ObjectCreated:*
        rules:
          - prefix: ${self:provider.stage}/dbo/orders/
        existing: true
  environment:
    LIVE_ORDERS_DB: ${ssm:/omni-pb-rt/${self:provider.stage}/orders/db}
    S3_BUCKET: ${ssm:/omni-realtime/${self:provider.stage}/lvlp/s3-bucket}
    REGION: ${self:provider.region}
