function:
  handler: src/realtime/ordersRT.handler 
  name: omni-live-real-time-orders-${self:provider.stage}
  description: LiVe Orders Table - ${self:provider.stage}
  runtime: python3.11
  layers:
    - {Ref: LiveUpdatesLambdaLayer}
  timeout: 600
  package:
    patterns:
      - '!**/*'
      - 'src/realtime/ordersRT.py'
      - 'src/shared/**'
  
  events:
    - s3:
        bucket: arn:aws:s3:::dms-dw-etl-lvlp/dev/dbo/
        event: s3:ObjectCreated:*
        rules:
          - prefix: orders/
        existing: true