function:
  handler: src/realtime/reprocess.handler 
  name: omni-live-real-time-reprocess-${self:provider.stage}
  description: LiVe reprocess - ${self:provider.stage}
  runtime: python3.11
  layers:
    - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python311:12
  timeout: 600
  package:
    patterns:
      - '!**/*'
      - 'src/realtime/reprocess.py'
      - 'src/shared/**'
  events:
    - stream:
        type: dynamodb
        arn: ${ssm:/omni-live-realtime/${self:provider.stage}/failed-records/ddb.streamArn~true}
        batchSize: 10
        startingPosition: LATEST
        filterPatterns:
          - { dynamodb: { NewImage: { Status: { S: ['INSERTED'] } } } }


