function:
  handler: src/realtime/stopRT.handler 
  name: omni-live-real-time-stop-${self:provider.stage}
  description: LiVe Stop Table - ${self:provider.stage}
  runtime: python3.11
  layers:
    - { Ref: PythonLayerLambdaLayer }
  timeout: 600
  package:
    patterns:
      - '!**/*'
      - 'src/realtime/stopRT.py'
      - 'src/shared/**'
  events:
    - s3:
        bucket: dms-dw-etl-lvlp
        event: s3:ObjectCreated:*
        rules:
          - prefix: dev/dbo/stop/
        existing: true
  environment:
    LIVE_STOPS_DB: ${ssm:/omni-pb-rt/${self:provider.stage}/stop/db}
    S3_BUCKET: 'dms-dw-etl-lvlp'
    REGION: ${self:provider.region}
