---
function:
  name: omni-movement-order-rt-ddb-to-sns-${self:provider.stage}
  handler: src/dynamoStreamToSns/movementorderrtstreamstosns.handler
  tags:
    Name : omni-movement-order-rt-ddb-to-sns-${self:provider.stage}
  runtime: python3.11
  layers:
    - { Ref: PythonPackagesLambdaLayer }
  package:
    patterns:
      - "!**/*"
      - "src/dynamoStreamToSns/movementorderrtstreamstosns.py"
      - "src/shared/**"
  events:
    - stream:
        type: dynamodb  
        arn : ${ssm:/omni-pb-rt/${self:provider.stage}/movement-order/ddb.streamArn}
  environment:
    SNS_TOPIC_ARN: ${ssm:/omni-live-rt-replication/${self:provider.stage}/movement-order-rt-ddb-to-sns/arn}
    DYNAMO_DB_TABLE: ${ssm:/omni-pb-rt/${self:provider.stage}/movement-order/db}


