---
function:
  name: omni-movement-Order-rt-ddb-to-sns-${self:provider.stage}
  handler: src/dynamoStreamToSns/movementOrderRTstreamstosns.handler
  runtime: python3.11
  layers:
    - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python311:12
  package:
    patterns:
      - "!**/*"
      - "src/dynamoStreamToSns/movementOrderRTstreamstosns.py"
      - "src/shared/**"
  events:
    - stream: "arn:aws:dynamodb:us-east-1:332281781429:table/omni-pb-rt-movement-order-dev/stream/2024-05-09T20:02:58.582"
  environment:
    SNS_TOPIC_ARN : "arn:aws:sns:us-east-1:332281781429:omni-live-rt-replication-movement-Order-rt-ddb-to-sns-dev"
    DYNAMO_DB_TABLE: "omni-pb-rt-movement-order-dev"


