---
function:
  name: omni-movement-rt-ddb-to-sns-${self:provider.stage}
  handler: src/dynamoStreamToSns/movementRTstreamstosns.handler
  runtime: python3.11
  tags: 
    Name : omni-movement-rt-ddb-to-sns-${self:provider.stage}
  layers:
    - { Ref: PythonPackagesLambdaLayer }
  package:
    patterns:
      - "!**/*"
      - "src/dynamoStreamToSns/movementRTstreamstosns.py"
      - "src/shared/**"
  events:
    - stream:
        type: dynamodb  
        arn : ${ssm:/omni-pb-rt/${self:provider.stage}/movement/ddb.streamArn}
 
  environment:
    SNS_TOPIC_ARN: ${ssm:/omni-live-rt-replication/${self:provider.stage}/movement-rt-ddb-to-sns/arn}
    DYNAMO_DB_TABLE: ${ssm:/omni-pb-rt/${self:provider.stage}/movement/db}
    
