---
function:
  name: omni-movement-Order-rt-ddb-to-sns-${self:provider.stage}
  handler: src/dynamoStreamToSns/movementOrderRTstreamstosns.handler
  runtime: python3.11
  layers:
    - { Ref: PythonLayerLambdaLayer }
  package:
    patterns:
      - "!**/*"
      - "src/dynamoStreamToSns/movementOrderRTstreamstosns.py"
      - "src/shared/**"
  events:
    - stream: "arn:aws:dynamodb:us-east-1:332281781429:table/omni-pb-rt-movement-order-dev/stream/2024-05-09T20:02:58.582"
  environment:
    SNS_TOPIC_ARN : ${ssm:/omni-live-rt-replication/${self:provider.stage}/movement-order-rt-ddb-to-sns/arn~true} 
    # DYNAMO_DB_TABLE: 

