---
function:
  name: omni-orders-rt-ddb-to-sns-${self:provider.stage}
  handler: src/dynamoStreamToSns/ordersrtstreamstosns.handler
  runtime: python3.10
  tags:
    Name : omni-orders-rt-ddb-to-sns-${self:provider.stage}
  layers:
    - { Ref: PythonPackagesLambdaLayer }
  package:
    patterns:
      - "!**/*"
      - "src/dynamoStreamToSns/ordersrtstreamstosns.py"
      - "src/shared/**"
  events:
    - stream:
        type: dynamodb  
        arn : ${ssm:/omni-pb-rt/${self:provider.stage}/orders/ddb.streamArn}
  environment:
    SNS_TOPIC_ARN: ${ssm:/omni-live-rt-replication/${self:provider.stage}/orders-rt-ddb-to-sns/arn}
    DYNAMO_DB_TABLE: ${ssm:/omni-pb-rt/${self:provider.stage}/orders/db}

