---
function:
  name: omni-orders-RT-ddb-to-sns-${self:provider.stage}
  handler: src/dynamoStreamToSns/ordersRTstreamstosns.handler
  runtime: python3.11
  layers:
    - { Ref: PythonLayerLambdaLayer }
  package:
    patterns:
      - "!**/*"
      - "src/dynamoStreamToSns/ordersRTstreamstosns.py"
      - "src/shared/**"
  events:
    - stream: 
  environment:
    SNS_TOPIC_ARN: ${ssm:/omni-live-rt-replication/${self:provider.stage}/orders-rt-ddb-to-sns/arn}
    DYNAMO_DB_TABLE: ${ssm:/omni-pb-rt/${self:provider.stage}/orders/db~true}

