---
function:
  name: omni-stop-rt-ddb-to-sns-${self:provider.stage}
  handler: src/dynamoStreamToSns/stop-rt-streams-to-sns.handler
  tags:
    Name : omni-stop-rt-ddb-to-sns-${self:provider.stage}
  layers:
    - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python311:12
  package:
    patterns:
      - "!**/*"
      - "src/dynamoStreamToSns/stop-rt-streams-to-sns.py"
      - "src/shared/**"
  events:
    - stream:
        type: dynamodb  
        arn : ${ssm:/omni-pb-rt/${self:provider.stage}/stop/ddb.streamArn}
  environment:
    SNS_TOPIC_ARN: ${ssm:/omni-live-rt-replication/${self:provider.stage}/stop-rt-ddb-to-sns/arn}
    DYNAMO_DB_TABLE: ${ssm:/omni-pb-rt/${self:provider.stage}/stop/db}
