---
function:
  name: omni-stop-RT-ddb-to-sns-${self:provider.stage}
  handler: src/dynamoStreamToSns/stopRTstreamstosns.handler
  runtime: python3.11
  layers:
    - { Ref: PythonLayerLambdaLayer }
  package:
    patterns:
      - "!**/*"
      - "src/dynamoStreamToSns/stopRTstreamstosns.py"
      - "src/shared/**"
  events:
    - stream: 
  environment:
    SNS_TOPIC_ARN: ${ssm:/omni-live-rt-replication/${self:provider.stage}/stop-rt-ddb-to-sns/arn}
    DYNAMO_DB_TABLE: ${ssm:/omni-pb-rt/${self:provider.stage}/stop/db~true}

